### ISSUE TITLE
Support QR codes or other printable code.

### ISSUE THREAD

**Issue by illegalprime** [HackGT/checkin#1]
This is for HackG4, and it can be done with: [QuaggaJS](https://serratus.github.io/quaggaJS/) or [Zebra Crossing](https://github.com/zxing/zxing), not a priority yet.

**Comment by petschekr** [comment]
@illegalprime Is this in the wrong checkin repo?

**Comment by bunsenmcdubbs** [comment]
Can confirm this is the wrong checkin repo.

Please take this to ultimate-checkin

**Comment by ghost** [comment]
Please take me off this email chain 😎🤷‍♀️

**Comment by illegalprime** [comment]
hi @amreetahub !
